name: MasterCI
on:
  push:
    branches:
      - master
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo I am from master-1,
        echo test, and deploy your project.
